package externaldata

import "time"

type wprdcFields struct {
	_id                       int
	PARID                     string
	PROPERTYHOUSENUM          string
	PROPERTYFRACTION          string
	PROPERTYADDRESS           string
	PROPERTYCITY              string
	PROPERTYSTATE             string
	PROPERTYUNIT              string
	PROPERTYZIP               string
	MUNICODE                  string
	MUNIDESC                  string
	SCHOOLCODE                string
	SCHOOLDESC                string
	LEGAL1                    string
	LEGAL2                    string
	LEGAL3                    string
	NEIGHCODE                 string
	NEIGHDESC                 string
	TAXCODE                   string
	TAXDESC                   string
	TAXSUBCODE                string
	TAXSUBCODE_DESC           string
	OWNERCODE                 string
	OWNERDESC                 string
	CLASS                     string
	CLASSDESC                 string
	USECODE                   string
	USEDESC                   string
	LOTAREA                   float64
	HOMESTEADFLAG             string
	CLEANGREEN                string
	FARMSTEADFLAG             string
	ABATEMENTFLAG             string
	RECORDDATE                string
	SALEDATE                  string
	SALEPRICE                 float64
	SALECODE                  string
	SALEDESC                  string
	DEEDBOOK                  string
	DEEDPAGE                  string
	PREVSALEDATE              string
	PREVSALEPRICE             float64
	PREVSALEDATE2             string
	PREVSALEPRICE2            float64
	CHANGENOTICEADDRESS1      string
	CHANGENOTICEADDRESS2      string
	CHANGENOTICEADDRESS3      string
	CHANGENOTICEADDRESS4      string
	COUNTYBUILDING            float64
	COUNTYLAND                float64
	COUNTYTOTAL               float64
	COUNTYEXEMPTBLDG          float64
	LOCALBUILDING             float64
	LOCALLAND                 float64
	LOCALTOTAL                float64
	FAIRMARKETBUILDING        float64
	FAIRMARKETLAND            float64
	FAIRMARKETTOTAL           float64
	STYLE                     string
	STYLEDESC                 string
	STORIES                   string
	YEARBLT                   float64
	EXTERIORFINISH            string
	EXTFINISH_DESC            string
	ROOF                      string
	ROOFDESC                  string
	BASEMENT                  string
	BASEMENTDESC              string
	GRADE                     string
	GRADEDESC                 string
	CONDITION                 string
	CONDITIONDESC             string
	CDU                       string
	CDUDESC                   string
	TOTALROOMS                float64
	BEDROOMS                  float64
	FULLBATHS                 float64
	HALFBATHS                 float64
	HEATINGCOOLING            string
	HEATINGCOOLINGDESC        string
	FIREPLACES                float64
	BSMTGARAGE                string
	FINISHEDLIVINGAREA        float64
	CARDNUMBER                float64
	ALT_ID                    string
	TAXYEAR                   float64
	ASOFDATE                  time.Time
	MUNICIPALITY              string
	NEIGHBORHOOD              string
	PGH_COUNCIL_DISTRICT      string
	PGH_WARD                  string
	PGH_PUBLIC_WORKS_DIVISION string
	PGH_POLICE_ZONE           string
	PGH_FIRE_ZONE             string
	TRACT                     string
	BLOCK_GROUP               string
}
